FROM ubuntu:18.04

USER root


# get a reasonable version of openvswitch
RUN apt-get update --fix-missing
RUN apt-get install -y iproute2 apt bash iperf iputils-ping tcpdump
RUN apt-get update
RUN apt-get install -y netcat net-tools 


