apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment
  labels:
    app: iperf-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf-server-tcp
        image: shaharklein/ub-iperf:latest
        ports:
        - containerPort: 5001
        env:
        command: ["/usr/bin/iperf"]
        args: ["-s"]
      - name: iperf-server-udp
        image: shaharklein/ub-iperf:latest
        ports:
        - containerPort: 5001
        env:
        command: ["/usr/bin/iperf"]
        args: ["-u -s"]

---
kind: Service
apiVersion: v1
metadata:
  name: iperf-server-service
spec:
  selector:
    app: iperf-server
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001

